num_waypoints_per_cluster: 5

tree_polygons_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/UdeM/xprize/20240521_zf2100ha_lowres_m3m/20240521_zf2100ha_highres_m3m_rgb_gr0p05_inferclassifier_fixed_subset.gpkg'
tree_polygons_layer: '20240521_zf2100ha_highres_m3m_rgb_gr0p05_inferclassifier_fixed_subset'

starting_point_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/UdeM/xprize/20240521_zf2100ha_lowres_m3m/starting_point.gpkg'
starting_point_layer: 'starting_point'

zone_of_interest_path: '/mnt/c/Users/vincent.le.falher/Downloads/UdeM/xprize/20240521_zf2100ha_lowres_m3m/zf2100ha_clusters_of_interest.gpkg'
zone_of_interest_layer: 'zone_of_insterest'

dsm_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/UdeM/xprize/20240521_zf2100ha_lowres_m3m/20240521_zf2100ha_lowres_m3m_dsm_subset.tif'

global_csv_file_path: '/home/vincelf/vscode-workspaces/lefolab-dji-waypoints/global_values.csv'
points_csv_file_path: '/home/vincelf/vscode-workspaces/lefolab-dji-waypoints/waypoints.csv'
