flight_height: 460
# <wpml:height>385.799987792969</wpml:height> Voir Google Earth qui est altitude orthométrique
# conversion GPSh NRCAN.GC.CA
point_dsm_height_buffer: 10

global_csv_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/20240620_gault_drone/20240529_sblz1z2_p1_global_values.csv'
points_csv_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/20240620_gault_drone/20240529_sblz1z2_p1_waypoints.csv'
shortest_path_csv_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/20240620_gault_drone/20240529_sblz1z2_p1_waypoints_shortest_path.csv'

kml_model_file_path: './scripts/wpml/model/example-mission-m3t-kmz/wpmz/template.kml'
output_kml_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/20240620_gault_drone/wpmz/template.kml'

wpml_model_file_path: 'scripts/wpml/model/example-mission-m3t-kmz/wpmz/waylines.wpml'
output_wpml_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/20240620_gault_drone/wpmz/waylines.wpml'

kmz_base_name: '20240620_gault_drone'
kmz_root_file_path: '/mnt/c/Users/vincent.le.falher/Downloads/'