num_waypoints_per_cluster: 5

tree_polygons_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1.gpkg'
tree_polygons_layer: 'trees_polygons'

starting_point_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1_starting_point.gpkg'
starting_point_layer: 'sblz1z2_starting_point'

zone_of_interest_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1_zone_of_interest.gpkg'
zone_of_interest_layer: '20240529_sblz1z2_p1_zone_of_interest'

dsm_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1_dsm_highdis.cog.tif'

global_csv_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1_global_values.csv'
points_csv_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/20240529_sblz1z2_p1_waypoints.csv'

kml_model_file_path: './scripts/wpml/model/Waypoint2/wpmz/template.kml'
output_kml_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/wpmz/template.kml'

wpml_model_file_path: 'scripts/wpml/model/Waypoint2/wpmz/waylines.wpml'
output_wpml_file_path: '/mnt/c/Users/User/Downloads/UdeM/xprize/20240529_sblz1z2_p1/wpmz/waylines.wpml'